version: '3.8'

services:

  rabbitmq:    
      image: rabbitmq:3-management
      container_name: rabbitmq-container
      ports:
        - "5672:5672"   # Porta do RabbitMQ
        - "15672:15672" # Porta de acesso à interface web
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

  api-creditos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-creditos
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/postgres
      - SPRING_DATASOURCE_USERNAME=spostgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres
      - rabbitmq  
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=spostgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"  # Mapeando a porta 5433 da máquina para a 5432 do container
    volumes:
      - postgres-data:/var/lib/postgresql/data

  

volumes:
  postgres-data:
    driver: local